### ISSUE TITLE
SaleDataCollection sem transações de boleto e cartão de crédito

### ISSUE THREAD

**Issue by gersonkm** [mundipagg/mundipagg-one-java#9]
Tenho uma pesquisa (método QueryOrder(orderReference)) que retorna um 'SaleData' com os fields 'BoletoTransactionDataCollection' e 'CreditCardTransactionDataCollection' **`null`**. 

Esse pedido deveria ter transações de **cartão de crédito**. 
No dashboard está tudo normal.

**Comment by rafaelsc** [comment]
@gersonkm Poderia entrar em contato com o Atendimento da Mundipagg para termos mais informações sobre essa Transação. Informando o seu MerchantKey e o seu OrderReference.
Pedindo para o atendimento encaminhar o chamado para Rafael Cordeiro. Irei analisar com mais calma esse caso.

**Comment by rafaelsc** [comment]
@gersonkm Não foi identificado problemas na SDK referente a isso. Entraremos em contato direto pelo suporte da Mundipagg para explicar melhor o ocorrido.

**Comment by gersonkm** [comment]
Ok! Obrigado.
